package com.isuwang.dapeng.metadata.beans;


/**
 * Autogenerated by Dapeng-Code-Generator (1.1.2)
*
* DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*  @generated

*
**/
public class FieldMeta {

    public String structName;
    public String getStructName() { return structName; }
    public void setStructName(String structName) { this.structName = structName; }
    public String structName() { return this.structName; }
    public FieldMeta structName(String structName) { this.structName = structName; return this; }
    /**
    *

idl 数据类型， primitive|list|map|set|struct|action，如“i32”、“list”，“TOrder”


ui元素，缺省时，会根据datatype和dataTypeExtra，提供默认ui：h2-text|h2-textarea|h2-select-list|h2-radio-group|h2-checkbox

    **/
    public String element;
    public String getElement(){ return this.element; }
    public void setElement(String element){ this.element = element; }

    public String element(){ return this.element; }
    public FieldMeta element(String element){ this.element = element; return this; }

    /**
    *

字段名，如“orderNo”

    **/
    public String name ;
    public String getName(){ return this.name; }
    public void setName(String name){ this.name = name; }

    public String name(){ return this.name; }
    public FieldMeta name(String name){ this.name = name; return this; }

    /**
    *

字段名，如“订单号”

    **/
    public String label;
    public String getLabel(){ return this.label; }
    public void setLabel(String label){ this.label = label; }

    public String label(){ return this.label; }
    public FieldMeta label(String label){ this.label = label; return this; }

    /**
    *

是否必填，true | false

    **/
    public boolean required ;
    public boolean getRequired(){ return this.required; }
    public void setRequired(boolean required){ this.required = required; }

    public boolean required(){ return this.required; }
    public FieldMeta required(boolean required){ this.required = required; return this; }

    /**
    *

多否多选，true | false

    **/
    public boolean mutil ;
    public boolean getMutil(){ return this.mutil; }
    public void setMutil(boolean mutil){ this.mutil = mutil; }

    public boolean mutil(){ return this.mutil; }
    public FieldMeta mutil(boolean mutil){ this.mutil = mutil; return this; }

    /**
    *

显示格式，用于日期显示，如“yyyy-MM-dd”

    **/
    public String format;
    public String getFormat(){ return this.format; }
    public void setFormat(String format){ this.format = format; }

    public String format(){ return this.format; }
    public FieldMeta format(String format){ this.format = format; return this; }

    /**
    *

是否可编辑，true|false

    **/
    public boolean editable ;
    public boolean getEditable(){ return this.editable; }
    public void setEditable(boolean editable){ this.editable = editable; }

    public boolean editable(){ return this.editable; }
    public FieldMeta editable(boolean editable){ this.editable = editable; return this; }

    /**
    *

前是否需要校验，true|false

    **/
    public boolean validate ;
    public boolean getValidate(){ return this.validate; }
    public void setValidate(boolean validate){ this.validate = validate; }

    public boolean validate(){ return this.validate; }
    public FieldMeta validate(boolean validate){ this.validate = validate; return this; }

    /**
    *

字符长度

    **/
    public int length;
    public int getLength(){ return this.length; }
    public void setLength(int length){ this.length = length; }

    public int length(){ return this.length; }
    public FieldMeta length(int length){ this.length = length; return this; }

    /**
    *

允许最大长度

    **/
    public int maxLength;
    public int getMaxLength(){ return this.maxLength; }
    public void setMaxLength(int maxLength){ this.maxLength = maxLength; }

    public int maxLength(){ return this.maxLength; }
    public FieldMeta maxLength(int maxLength){ this.maxLength = maxLength; return this; }

    /**
    *

允许最小长度

    **/
    public int minLength;
    public int getMinLength(){ return this.minLength; }
    public void setMinLength(int minLength){ this.minLength = minLength; }

    public int minLength(){ return this.minLength; }
    public FieldMeta minLength(int minLength){ this.minLength = minLength; return this; }

    /**
    *

正则匹配

    **/
    public String regexp;
    public String getRegexp(){ return this.regexp; }
    public void setRegexp(String regexp){ this.regexp = regexp; }

    public String regexp(){ return this.regexp; }
    public FieldMeta regexp(String regexp){ this.regexp = regexp; return this; }

    /**
    *

校验失败时的提示语，如“请输入备注”

    **/
    public String prompt;
    public String getPrompt(){ return this.prompt; }
    public void setPrompt(String prompt){ this.prompt = prompt; }

    public String prompt(){ return this.prompt; }
    public FieldMeta prompt(String prompt){ this.prompt = prompt; return this; }

    /**
    *

数字最小值

    **/
    public int min;
    public int getMin(){ return this.min; }
    public void setMin(int min){ this.min = min; }

    public int min(){ return this.min; }
    public FieldMeta min(int min){ this.min = min; return this; }

    /**
    *

数字最大值

    **/
    public int max;
    public int getMax(){ return this.max; }
    public void setMax(int max){ this.max = max; }

    public int max(){ return this.max; }
    public FieldMeta max(int max){ this.max = max; return this; }

    /**
    *

placeholder

    **/
    public String placeholder;
    public String getPlaceholder(){ return this.placeholder; }
    public void setPlaceholder(String placeholder){ this.placeholder = placeholder; }

    public String placeholder(){ return this.placeholder; }
    public FieldMeta placeholder(String placeholder){ this.placeholder = placeholder; return this; }

    /**
    *

候选值，下拉选项中的值，json串，如 "[{value:1,label:'男'},{value:2,label:'女'}]"

    **/
    public String candidates;
    public String getCandidates(){ return this.candidates; }
    public void setCandidates(String candidates){ this.candidates = candidates; }

    public String candidates(){ return this.candidates; }
    public FieldMeta candidates(String candidates){ this.candidates = candidates; return this; }

    /**
    *

组件显示字段名，针对下拉组件、radio-group组件等，“label”

    **/
    public String candidateLabel;
    public String getCandidateLabel(){ return this.candidateLabel; }
    public void setCandidateLabel(String candidateLabel){ this.candidateLabel = candidateLabel; }

    public String candidateLabel(){ return this.candidateLabel; }
    public FieldMeta candidateLabel(String candidateLabel){ this.candidateLabel = candidateLabel; return this; }

    /**
    *

组件值字段名，针对下拉组件、radio-group组件等，“value”

    **/
    public String candidateValue;
    public String getCandidateValue(){ return this.candidateValue; }
    public void setCandidateValue(String candidateValue){ this.candidateValue = candidateValue; }

    public String candidateValue(){ return this.candidateValue; }
    public FieldMeta candidateValue(String candidateValue){ this.candidateValue = candidateValue; return this; }

    /**
    *

源字段名,如 "orderNum"

    **/
    public String srcKey;
    public String getSrcKey(){ return this.srcKey; }
    public void setSrcKey(String srcKey){ this.srcKey = srcKey; }

    public String srcKey(){ return this.srcKey; }
    public FieldMeta srcKey(String srcKey){ this.srcKey = srcKey; return this; }

    /**
    *

界面是否可见，仅对表单中的字段有效， 默认true

    **/
    public boolean visible ;
    public boolean getVisible(){ return this.visible; }
    public void setVisible(boolean visible){ this.visible = visible; }

    public boolean visible(){ return this.visible; }
    public FieldMeta visible(boolean visible){ this.visible = visible; return this; }

    /**
    *

是否禁用组件

    **/
    public boolean disabled ;
    public boolean getDisabled(){ return this.disabled; }
    public void setDisabled(boolean disabled){ this.disabled = disabled; }

    public boolean disabled(){ return this.disabled; }
    public FieldMeta disabled(boolean disabled){ this.disabled = disabled; return this; }


public String toString(){
  StringBuilder stringBuilder = new StringBuilder("{");
  stringBuilder.append("\"").append("structName").append("\":\"").append(this.structName).append("\",");
  stringBuilder.append("\"").append("element").append("\":\"").append(this.element).append("\",");
stringBuilder.append("\"").append("name").append("\":\"").append(this.name).append("\",");
stringBuilder.append("\"").append("label").append("\":\"").append(this.label).append("\",");
stringBuilder.append("\"").append("required").append("\":").append(this.required).append(",");
stringBuilder.append("\"").append("mutil").append("\":").append(this.mutil).append(",");
stringBuilder.append("\"").append("format").append("\":\"").append(this.format).append("\",");
stringBuilder.append("\"").append("editable").append("\":").append(this.editable).append(",");
stringBuilder.append("\"").append("validate").append("\":").append(this.validate).append(",");
stringBuilder.append("\"").append("length").append("\":").append(this.length).append(",");
stringBuilder.append("\"").append("maxLength").append("\":").append(this.maxLength).append(",");
stringBuilder.append("\"").append("minLength").append("\":").append(this.minLength).append(",");
stringBuilder.append("\"").append("regexp").append("\":\"").append(this.regexp).append("\",");
stringBuilder.append("\"").append("prompt").append("\":\"").append(this.prompt).append("\",");
stringBuilder.append("\"").append("min").append("\":").append(this.min).append(",");
stringBuilder.append("\"").append("max").append("\":").append(this.max).append(",");
stringBuilder.append("\"").append("placeholder").append("\":\"").append(this.placeholder).append("\",");
stringBuilder.append("\"").append("candidates").append("\":\"").append(this.candidates).append("\",");
stringBuilder.append("\"").append("candidateLabel").append("\":\"").append(this.candidateLabel).append("\",");
stringBuilder.append("\"").append("candidateValue").append("\":\"").append(this.candidateValue).append("\",");
stringBuilder.append("\"").append("srcKey").append("\":\"").append(this.srcKey).append("\",");
stringBuilder.append("\"").append("visible").append("\":").append(this.visible).append(",");
stringBuilder.append("\"").append("disabled").append("\":").append(this.disabled).append(",");

  stringBuilder.deleteCharAt(stringBuilder.lastIndexOf(","));
  stringBuilder.append("}");

  return stringBuilder.toString();
}
}
      